### ISSUE TITLE
Firebase database json not avilable

### ISSUE THREAD

**Issue by suresh-ums** [rudreshmehta/Ecommerce-Firebase-app#3]
Please provide firebase database exported json file so we can start with amazing code

**Comment by abhishekraics001** [comment]
ERROR: File google-services.json is missing. The Google Services Plugin cannot function without it.

**Comment by bukyapavankumar** [comment]
> ERROR: File google-services.json is missing. The Google Services Plugin cannot function without it.

U need to setup firebase auth

**Comment by bukyapavankumar** [comment]
@suresh-ums  do u have the json file or file format
